/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.ImmutableMap;

import java.util.Map;

/**
 * To start the application:
 * ./gradlew build
 * java -jar ./hw01-gradle/build/libs/gradleHelloOtus-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l hw01-gradle.jar
 * unzip -l gradleHelloOtus-0.1.jar
 */
public class HelloOtus {
    public static void main(String... args) {
        Map<String, Integer> salaries = ImmutableMap.<String, Integer>builder()
                .put("John", 1000)
                .put("Jane", 1500)
                .put("Adam", 2000)
                .put("Tom", 2000)
                .build();

        salaries.forEach(HelloOtus::printSalary);
    }

    private static void printSalary(String name, Integer salary) {
        System.out.printf("%s: %s%n", name, salary);
    }
}
